config/routes.rb
Designbuild::Application.routes.draw do
  
  resources :resource_allocations

  resources :resource_requests

  resources :resources do
    resources :resource_allocations
  end

  resources :invoices do
    resources :invoice_lines
    resources :invoice_lines, :as => :line_items
    resources :invoice_markup_lines
    resources :invoice_markup_lines, :as => :markups
    
    member do
      get :start
      get :assign_costs
      get :set_amounts
      get :add_markups
      get :select_template
      get :finished
      
      get :accept_costs
      get :accept_markups
    end
  end  

  resources :payments do
    resources :payment_lines
    resources :payment_lines, :as => :line_items
    resources :payment_markup_lines
    resources :payment_markup_lines, :as => :markups

    member do
      get :start
      get :balance
      get :finished
      
      get :accept
    end
  end
    
  resources :milestones

  resources :suppliers
  
  resources :laborers  
  
  resources :projects do
    resources :components do
      member do
        get :changelog
        get :new_cost
        post :sort
      end
      collection do
        post :sort
      end
    end
    resources :tasks        # re-nested
    
    resources :contracts do
      collection do
        post :sort
      end
    end
        
    resources :invoices     # re-nested
    resources :payments     # re-nested
    
    resources :resource_requests
    
    member do
      post :add_markup, :as => :add_markup_to
      get :autocomplete_task_name
    end
    
    resources :markups do
      member do
        get :add, :action => :add_to_project
        get :remove, :action => :remove_from_project
      end
    end
    
    member do
      get :timeline, :as => :timeline_for
      get :estimate_report, :as => :estimate_report_for
      get :cost_report, :as => :cost_report_for
      get :purchase_order_list, :as => :purchase_order_list_for
      get :labor_summary, :as => :labor_summary_for
      get :payroll_summary, :as => :payroll_summary_for
      get :material_cost_summary, :as => :material_cost_summary_for
      get :invoicing
    end
    
    collection do
      get :purchase_order_list
      get :labor_summary
      get :payroll_summary
      get :material_cost_summary
    end
  end

  resources :components do
    resources :quantities
    resources :fixed_cost_estimates
    resources :unit_cost_estimates
    resources :contracts
    resources :markups
    resources :components, :as => :subcomponents, :path => :subcomponents
    
    member do
      post :add_markup, :as => :add_markup_to
      get :changelog
    end
    
    resources :markups, :only => [:new, :create, :edit, :update] do
      member do
        get :add, :action => :add_to_component
        get :remove, :action => :remove_from_component
      end
    end
  end
    
  resources :tasks do
    resources :labor_costs        # re-nested
    resources :material_costs     # re-nested

    member do
      post :add_markup, :as => :add_markup_to
      get :estimated_costs
      get :costs
    end
    
    resources :markups do
      member do
        get :add, :action => :add_to_task
        get :remove, :action => :remove_from_task
      end
    end
    
    resources :unit_cost_estimates do
      member do
        get :add, :action => :add_to_task
        get :remove, :action => :remove_from_task
      end
    end
    
    resources :fixed_cost_estimates do
      member do
        get :add, :action => :add_to_task
        get :remove, :action => :remove_from_task
      end
    end
  end
    
  resources :labor_costs do    
    resources :labor_cost_lines, :as => :line_items
    
    collection do
      get :overview
    end
  end
  
  resources :material_costs do
    resources :material_cost_lines, :as => :line_items
    get :autocomplete_supplier_name, :on => :collection
  end
  
  resources :contracts do
    resources :bids
    resources :contract_costs

    member do
      post :add_markup, :as => :add_markup_to
    end
    
    resources :markups do
      member do
        get :add, :action => :add_to_contract
        get :remove, :action => :remove_from_contract
      end
    end
  end

  resources :tags
  
  resources :markups
  
  namespace :admin do
    resources :users
  end
  
  devise_for :users
  
  
  match 'reports', :controller => :reports, :action => :index, :as => :reports
  match 'reports/:action', :controller => :reports
  

  root :to => "projects#index"
  

end

app/models/task.rb
class Task < ActiveRecord::Base
  include AddOrNil
  
  has_paper_trail :ignore => [:created_at, :updated_at]
  
  belongs_to :contract, :inverse_of => :tasks
  belongs_to :project, :inverse_of => :tasks
  
  has_many :unit_cost_estimates, :order => :name
  has_many :fixed_cost_estimates, :order => :name
  has_many :labor_costs, :order => 'date DESC', :dependent => :destroy
  has_many :material_costs, :order => 'date DESC', :dependent => :destroy

  has_many :markings, :as => :markupable, :dependent => :destroy
  has_many :markups, :through => :markings, :dependent => :destroy, :after_remove => :cascade_remove
  
  has_many :estimated_cost_points, :as => :source, :class_name => 'DatePoint', :order => :date, :conditions => {:series => :estimated_cost}, :dependent => :destroy
  has_many :projected_cost_points, :as => :source, :class_name => 'DatePoint', :order => :date, :conditions => {:series => :projected_cost}, :dependent => :destroy
  has_many :cost_to_date_points, :as => :source, :class_name => 'DatePoint', :order => :date, :conditions => {:series => :cost_to_date}, :dependent => :destroy
  
  validates_presence_of :name, :project

  after_create :inherit_markups
  
  #before_save :create_estimated_cost_points, :if => proc {|i| i.estimated_cost_changed? && ( !i.new_record? || ( !i.estimated_cost.nil? && i.estimated_cost > 0 ) )}
  #before_save :create_projected_cost_points, :if => proc {|i| i.projected_cost_changed? && ( !i.new_record? || ( !i.projected_cost.nil? && i.projected_cost > 0 ) )}
  # cost to date points being created at cost creation
  #before_save :create_cost_to_date_points, :if => proc {|i| i.cost_changed? && ( !i.new_record? || ( !i.cost.nil? && i.cost > 0 ) )}

  after_save :update_invoicing_state
  
  after_destroy :clear_associated
  
  scope :active, lambda {
    where(:active => true)
  }
  
  scope :completed, lambda {
    #where( "#{table_name}.percent_complete >= 100" )
    where(:active => false)
  }
  
  scope :future, lambda {
    #where(:percent_complete => 0).where(:active => false)
    where(:active => nil)
  }
  
  
  def is_complete?
    self.percent_complete >= 100
  end
  
  def percent_complete_float
    self.percent_complete / 100
  end
  
  def percent_of_estimated
    multiply_or_nil(100, divide_or_nil(self.cost, self.estimated_cost))
  end
  
  def cost_estimates
    self.unit_cost_estimates.all + self.fixed_cost_estimates.all
  end
  
  def costs
    self.labor_costs.all + self.material_costs.all
  end
  
  def purchase_orders
    self.material_costs.where( :material_costs => {:raw_cost => nil} )
  end
  
  def completed_purchases
    self.material_costs.where( "material_costs.raw_cost IS NOT NULL" )
  end
  
  def projected_net
    self.estimated_cost - self.raw_projected_cost
  end

  def component_projected_net
    self.component_estimated_cost - self.raw_projected_cost
  end

  def labor_cost_before( date = Date::today )
    raw_labor_cost_before(date) + self.labor_costs.joins(:line_items => :markings).where( "labor_costs.date <= ?", date ).sum('markings.cost_markup_amount').to_f
  end
    
  def raw_labor_cost_before( date = Date::today )
    self.labor_costs.joins(:line_items).where( "labor_costs.date <= ?", date ).sum('labor_cost_lines.raw_cost').to_f
  end
    
  def material_cost_before( date = Date::today )
    raw_material_cost_before(date) + self.material_costs.joins(:markings).where( "material_costs.date <= ?", date ).sum('markings.cost_markup_amount').to_f
  end
    
  def raw_material_cost_before( date = Date::today )
    self.material_costs.where( "material_costs.date <= ?", date ).sum('material_costs.raw_cost').to_f
  end
    
  def cost_before(date)
    labor_cost_before(date) + material_cost_before(date)
  end
  
  def raw_cost_before(date)
    raw_labor_cost_before(date) + raw_material_cost_before(date)
  end
  
  
  # Invoicing
  
  def labor_percent
    100 * ( divide_or_nil( self.labor_cost, self.cost ) || 0 )
  end
  
  def labor_percent_before(date)
    100 * ( divide_or_nil(self.labor_cost_before(date), self.cost_before(date) ) || 0)
  end
  
  def material_percent
    100 * ( divide_or_nil( self.material_cost, self.cost ) || 0 )
  end
  
  def material_percent_before(date)
    100 * (divide_or_nil(self.labor_cost_before(date), self.cost_before(date) ) || 0)
  end
      
  def create_estimated_cost_points
    p = self.estimated_cost_points.find_or_initialize_by_date(Date::today)
    if p.label.nil?
      p.series = :estimated_cost
      p.value = self.estimated_cost || 0
      p.save!
    end
  end
    
  def create_projected_cost_points
    p = self.projected_cost_points.find_or_initialize_by_date(Date::today)
    if p.label.nil?
      p.series = :projected_cost
      p.value = self.projected_cost || 0
      p.save!
    end
  end
  
  def create_cost_to_date_points(date)
    p = self.cost_to_date_points.find_or_create_by_date(date)
    if p.label.nil?
      p.series = :cost_to_date
      p.value = self.labor_cost_before(date) + self.material_cost_before(date)
      #p.value = self.cost_before(date)
      p.save!
    end
  end
    
  def estimated_unit_cost
    estimated_raw_unit_cost + self.unit_cost_estimates.joins(:markings).sum('markings.estimated_cost_markup_amount').to_f
  end
  def estimated_fixed_cost
    estimated_raw_fixed_cost + self.fixed_cost_estimates.joins(:markings).sum('markings.estimated_cost_markup_amount').to_f
  end
  def estimated_cost
    estimated_unit_cost + estimated_fixed_cost
  end

  def estimated_raw_unit_cost
    self.unit_cost_estimates.sum('unit_cost_estimates.raw_cost').to_f
  end
  def estimated_raw_fixed_cost
    self.fixed_cost_estimates.sum('fixed_cost_estimates.raw_cost').to_f
  end
  def estimated_raw_cost
    estimated_raw_unit_cost + estimated_raw_fixed_cost
  end
  
  def labor_cost
    raw_labor_cost + self.labor_costs.joins(:line_items => :markings).sum('markings.cost_markup_amount').to_f
  end
  def material_cost
    raw_material_cost + self.material_costs.joins(:markings).sum('markings.cost_markup_amount').to_f
  end
  def cost
    labor_cost + material_cost
  end

  def raw_labor_cost
    self.labor_costs.joins(:line_items).sum('labor_cost_lines.raw_cost').to_f
  end
  def raw_material_cost
    self.material_costs.sum('material_costs.raw_cost').to_f
  end
  def raw_cost
    raw_labor_cost + raw_material_cost
  end

  def projected_cost
    if self.percent_complete >= 100
      self.cost
    else
      est = self.estimated_cost
      act = self.cost
      
      if act.nil?
        est
      elsif est.nil?
        act
      elsif act > est
        act
      else
        est
      end
    end
  end
      
  def raw_projected_cost
    if self.percent_complete >= 100
      self.raw_cost
    else
      est = self.estimated_raw_cost
      act = self.raw_cost
      
      if act.nil?
        est
      elsif est.nil?
        act
      elsif act > est
        act
      else
        est
      end
    end
  end
  
  def cascade_add(markup)
    LaborCostLine.where("labor_set_id in (?)", self.labor_cost_ids).each {|i| Marking.create :markup => markup, :markupable => i }
    self.material_costs.each {|i| Marking.create :markup => markup, :markupable => i }
  end
  
  def cascade_remove(markup)
    Marking.where(:markupable_type => 'LaborCostLine', :markup_id => markup.id).where( "markupable_id in (?)", LaborCostLine.where("labor_set_id in (?)", self.labor_cost_ids).map(&:id) ).delete_all
    Marking.where(:markupable_type => 'MaterialCost', :markup_id => markup.id).where( "markupable_id in (?)", self.material_cost_ids ).delete_all
  end
  
  protected
  
  def update_invoicing_state
    self.project.invoices.each {|i| i.save!}
    self.project.payments.each {|i| i.save!}
  end
        
  def inherit_markups
    self.project.markups(true).each {|m| self.markups << m unless self.markups.include?(m)}
  end
  
  def clear_associated
    self.fixed_cost_estimates.each {|fc| fc.task= nil; fc.save!}
    self.unit_cost_estimates.each {|uc| uc.task = nil; uc.save!}
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  #before_filter :get_project, :except => :add_markup
  before_filter :get_objects
  
  def add_markup
    @task = Task.find(params[:id])
    
    respond_to do |format|
      if @task.markups << Markup.find(params[:markup_id])
        format.html { redirect_to([@task.project, @task], :notice => 'Markup was successfully added.') }
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  # GET /tasks
  # GET /tasks.xml
  def index
    @tasks = @project.tasks

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tasks }
    end
  end
  
  def scheduling
    @task = Task.find(params[:id])
    @inactive_markups = Markup.scoped - @task.markups
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task }
    end
  end
  
  def estimated_costs
    @task = Task.find(params[:id])
    @inactive_markups = Markup.scoped - @task.markups
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task }
    end
  end
  
  def costs
    @task = Task.find(params[:id])
    @inactive_markups = Markup.scoped - @task.markups
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task }
    end
  end
  
  # GET /tasks/1
  # GET /tasks/1.xml
  def show
    @task = Task.find(params[:id])
    @inactive_markups = Markup.scoped - @task.markups
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.xml
  def new
    @task = Task.new

    respond_to do |format|
      format.js
      format.html # new.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.xml
  def create
    @task = Task.new(params[:task])
    @task.project = @project

    respond_to do |format|
      if @task.save
        format.js { 
          @tasks = @project.tasks
        }
        format.html { redirect_to([@project, @task], :notice => 'Task was successfully created.') }
        format.xml  { render :xml => @task, :status => :created, :location => @task }
      else
        format.js
        format.html { render :action => "new" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.xml
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.js { 
          if params[:render_nothing]
            render :nothing => true
          else
            @tasks = @project.tasks
          end
        }
        format.html { redirect_from_session_or([@project, @task], :notice => 'Task was successfully updated.') }
        format.xml  { head :ok }
      else
        format.js
        format.html { render :action => "edit" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.xml
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to(project_tasks_url(@project)) }
      format.xml  { head :ok }
    end
  end
  
  protected
  
  def get_objects
    @task = Task.find(params[:id]) if params.has_key? :id
    @project = Project.find(params[:project_id]) if params.has_key? :project_id
    
    @project ||= @task.project unless @task.nil?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_nav.html.haml
-current ||= nil
%h1
  Task: 
  =link_to @task.name, @task

%ul.nav
  %li{:class => current == :summary ? 'current' : nil}=link_to "Summary", @task
  %li{:class => current == :estimated_costs ? 'current' : nil}=link_to "Estimated Costs", estimated_costs_task_path( @task )
  %li{:class => current == :markups ? 'current' : nil}=link_to "Markups(#{@task.markups.count})", task_markups_path(@task)
  %li{:class => current == :costs ? 'current' : nil}=link_to "Costs", costs_task_path( @task )
  %li{:class => current == :edit ? 'current' : nil}=link_to 'Edit Task', edit_task_path(@task)
%hr

app/views/tasks/_task_list.html.haml
%table.tasks
  %tr
    %th Name
    %th.currency Est. Cost
    %th.currency Markup
    %th.currency Cost-to-Date
    %th.currency.qtip_projected Projected Cost
    %th.currency.qtip_net Net
    %th.number % Complete (Est./Act.)
    %th.check_box Active
    %th Deadline
    %th.control
    %th.control

  - tasks.each do |task|
    %tr{:id => "task_#{task.id}"}
      %td= link_to task.name, [@project, task]
      %td.currency= number_to_currency(task.estimated_raw_cost)
      %td.currency= number_to_currency( subtract_or_nil(task.estimated_cost, task.estimated_raw_cost ) )
      %td.currency= number_to_currency(task.cost)
      %td.currency= number_to_currency(task.projected_cost)
      %td.currency{:class => (!task.projected_net.nil? && task.projected_net < 0 ? 'negative' : nil)}= number_to_currency task.projected_net
      %td.number
        = number_to_percentage( task.percent_complete, :precision => 0 )
        ='/'
        = number_to_percentage( multiply_or_nil( 100, divide_or_nil(task.projected_cost, task.estimated_cost )), :precision => 0) || '--'
        
      %td.check_box
        =form_for [@project, task], :url => project_task_path(@project, task, :redirect_to => project_tasks_path(@project)), :html => {:id => "edit_task_#{task.id}_active"} do |f|
          = f.check_box :active, :onchange => "$('#edit_task_#{task.id}_active').submit();"
      %td
        -if task.deadline.blank?
          Set Deadline:
          = link_to 'New', new_task_deadline_path(task, :context => 'tasks'), :remote => true
          or
          =form_for [@project,task], :url => project_task_path(@project, task, :redirect_to => project_tasks_path(@project)), :html => {:id => "edit_task_#{task.id}_deadline"} do |f|
            =f.collection_select :deadline_id, @project.deadlines, :id, :select_label_short, {:include_blank => 'Existing'}, :onchange => "$('#edit_task_#{task.id}_deadline').submit();"
        -else
          = link_to( task.deadline.name, edit_task_deadline_path(task, :context => 'tasks'), :remote => true ) 
          = date_relative_to_now(task.deadline.date)
          = form_for [@project, task], :url => project_task_path(@project, task, :redirect_to => project_tasks_path(@project)) do |f|
            = f.hidden_field :deadline_id, :value => nil
            = f.submit 'Remove'
      %td.control.edit= link_to 'Edit', edit_project_task_path(@project, task, :context => 'tasks'), :remote => true
      %td.control.destroy= link_to icon(:delete), [@project, task], :confirm => 'Are you sure?', :method => :delete
      
  - if tasks.empty?
    %tr
      %td{:colspan => 12} (None)
      
  %tr.control.add_button
    %td{:colspan => 12}
      = link_to new_project_task_path(@project), :remote => true do
        =icon :add
        Add Task
      
  %tr.totals
    %td
      %strong Total
    %td.currency
      %strong= number_to_currency( tasks.inject(0) {|memo,obj| add_or_nil memo, obj.estimated_raw_cost })
    %td.currency
      %strong= number_to_currency( tasks.inject(nil) {|memo,obj| add_or_nil memo, subtract_or_nil(obj.estimated_cost, obj.estimated_raw_cost) } )
    %td.currency
      %strong= number_to_currency( tasks.inject(0) {|memo,obj| add_or_nil memo, obj.cost })
    %td.currency
      %strong= number_to_currency( tasks.inject(0) {|memo,obj| add_or_nil memo, obj.projected_cost })
    %td.currency
      %strong= number_to_currency( tasks.inject(0) {|memo,obj| add_or_nil memo, obj.projected_net })
    %td.number
      %strong
        ='--/'
        = tasks.inject(0) {|memo,obj| add_or_nil memo, obj.estimated_cost} == 0 ? nil : number_to_percentage(100 * (tasks.inject(0) {|memo,obj| add_or_nil memo, obj.cost}) / (tasks.inject(0) {|memo,obj| add_or_nil memo, obj.estimated_cost}), :precision => 1)
    %td{:colspan => 10}
    

app/views/tasks/_task_list_cost_plus.html.haml
%table.tasks
  %tr
    %th Name
    %th.currency Est. Cost
    %th.currency Cost-to-Date
    %th.currency.qtip_projected Projected Cost
    %th.number % Complete (Est./Act.)
    %th Status
    / %th.check_box Active
    %th.control
    %th.control

  - tasks.each do |task|
    %tr{:id => "task_#{task.id}"}
      %td= link_to task.name, [@project, task]
      / Est. Cost
      %td.currency= number_to_currency(task.estimated_cost)
      / Cost-to-Date
      %td.currency= number_to_currency(task.cost)
      / Projected Cost
      %td.currency= number_to_currency(task.projected_cost)
      / % Complete
      %td.number
        = number_to_percentage( task.percent_complete, :precision => 0 )
        ='/'
        = number_to_percentage( multiply_or_nil( 100, divide_or_nil(task.cost, task.estimated_cost )), :precision => 0) || '--'
      %td
        =form_for [@project, task], :url => project_task_path(@project,task, :render_nothing => true), :remote => true do |f|
          
          =f.radio_button :active, nil, {:onchange => '$(this.form).submit();'}
          =f.label 'Future'
          
          =f.radio_button :active, true, {:onchange => '$(this.form).submit();'}
          =f.label 'Active'
          
          =f.radio_button :active, false, {:onchange => '$(this.form).submit();'}
          =f.label 'Complete'
      / 
        Active
        %td.check_box
          =form_for [@project, task], :url => project_task_path(@project, task, :redirect_to => project_tasks_path(@project)), :html => {:id => "edit_task_#{task.id}_active"} do |f|
            = f.check_box :active, :onchange => "$('#edit_task_#{task.id}_active').submit();"
      %td.control.edit= link_to 'Edit', edit_project_task_path(@project, task, :context => 'tasks'), :remote => true
      %td.control.destroy= link_to icon(:delete), [@project, task], :confirm => 'Are you sure?', :method => :delete
      
  - if tasks.empty?
    %tr
      %td{:colspan => 12} (None)
      
  %tr.totals
    %td
      %strong Total
    %td.currency
      %strong= number_to_currency( tasks.map(&:estimated_cost).sum )
    %td.currency
      %strong= number_to_currency( tasks.map(&:cost).sum )
    %td.currency
      %strong= number_to_currency( tasks.map(&:projected_cost).sum )
    %td.number
      %strong
        ='--/'
        = tasks.inject(0) {|memo,obj| add_or_nil memo, obj.estimated_cost} == 0 ? nil : number_to_percentage(100 * (tasks.inject(0) {|memo,obj| add_or_nil memo, obj.cost}) / (tasks.inject(0) {|memo,obj| add_or_nil memo, obj.estimated_cost}), :precision => 1)
    %td{:colspan => 10}

app/views/tasks/_task_list_fixed_bid.html.haml
%table.tasks
  %tr
    %th Name
    %th.currency Est. Cost (marked up)
    %th.currency Cost-to-Date (raw)
    %th.currency.qtip_projected Projected Cost (raw)
    %th.currency Est. Net
    %th.currency.qtip_net Net to Date
    %th.number % Complete (Est./Act.)
    / %th.check_box Active
    %th.control
    %th.control

  - tasks.each do |task|
    %tr{:id => "task_#{task.id}"}
      %td= link_to task.name, [@project, task]
      / Est. Cost
      %td.currency= number_to_currency(task.estimated_cost)
      / Cost-to-Date
      %td.currency= number_to_currency(task.raw_cost)
      / Projected Cost
      %td.currency.de_emphasize= number_to_currency(task.raw_projected_cost)
      / Est. Net
      / (Should be based on estimates)
      %td.currency= number_to_currency( task.estimated_cost - task.estimated_raw_cost )
      / Net
      %td.currency{:class => (!task.projected_net.nil? && task.projected_net < 0 ? 'negative' : nil)}= number_to_currency task.projected_net
      / % Complete
      %td.number
        = number_to_percentage( task.percent_complete, :precision => 0 )
        ='/'
        = number_to_percentage( multiply_or_nil( 100, divide_or_nil(task.cost, task.estimated_raw_cost )), :precision => 0) || '--'
      / 
        Active
        %td.check_box
          =form_for [@project, task], :url => project_task_path(@project, task, :redirect_to => project_tasks_path(@project)), :html => {:id => "edit_task_#{task.id}_active"} do |f|
            = f.check_box :active, :onchange => "$('#edit_task_#{task.id}_active').submit();"
      %td.control.edit= link_to 'Edit', edit_project_task_path(@project, task, :context => 'tasks'), :remote => true
      %td.control.destroy= link_to icon(:delete), [@project, task], :confirm => 'Are you sure?', :method => :delete
      
  - if tasks.empty?
    %tr
      %td{:colspan => 12} (None)
      
  %tr.totals
    %td
      %strong Total
    %td.currency
      %strong= number_to_currency( tasks.map(&:estimated_raw_cost).sum )
    %td.currency
      %strong= number_to_currency( tasks.map(&:cost).sum )
    %td.currency
      %strong= number_to_currency( tasks.map(&:projected_cost).sum )
    %td.currency
      %strong= number_to_currency( tasks.inject(0) {|memo,obj| add_or_nil memo, subtract_or_nil(obj.estimated_cost, obj.estimated_raw_cost ) })
    %td.currency
      %strong= number_to_currency( tasks.inject(0) {|memo,obj| add_or_nil memo, obj.projected_net })
    %td.number
      %strong
        ='--/'
        = tasks.inject(0) {|memo,obj| add_or_nil memo, obj.estimated_raw_cost} == 0 ? nil : number_to_percentage(100 * (tasks.inject(0) {|memo,obj| add_or_nil memo, obj.cost}) / (tasks.inject(0) {|memo,obj| add_or_nil memo, obj.estimated_raw_cost}), :precision => 1)
    %td{:colspan => 10}

app/views/tasks/estimated_costs.html.haml
-content_for :head do
  =javascript_include_tag "autocomplete-rails.js"
  =javascript_include_tag "jquery.dimscreen.js"
  =stylesheet_link_tag 'jquery.theme.css', :media => 'screen, projection'
  
=render :partial => 'shared/project_nav', :locals => {:current => :tasks}

.container
  =render :partial => 'nav', :locals => {:current => :estimated_costs}

  %h2 Estimated Costs
  
  -@task.unit_cost_estimates.each do |unit_cost|
    =render :partial => 'unit_cost_estimates/list_div', :locals => {:unit_cost => unit_cost}
    
  -@task.fixed_cost_estimates.each do |fixed_cost|
    =render :partial => 'fixed_cost_estimates/list_div', :locals => {:fixed_cost => fixed_cost}
  
  -if @task.unit_cost_estimates.empty? && @task.fixed_cost_estimates.empty?
    .cost
      %h3.left No Estimated Costs associated with this Task
    
  =link_to '#add_estimated_costs', :class => 'click_to_show' do
    %button 
      =icon :add
      Add Estimated Costs
      
  #add_estimated_costs
    -@project.component_tree.each do |c|
      -uc = c.unit_cost_estimates - @task.fixed_cost_estimates
      -fc = c.fixed_cost_estimates - @task.fixed_cost_estimates
      -unless uc.empty? && fc.empty?
        %h3=c.name
        -uc.each do |unit_cost|
          =link_to unit_cost.name, add_task_unit_cost_estimate_path(@task, unit_cost)
        -fc.each do |fixed_cost|
          =link_to fixed_cost.name, add_task_fixed_cost_estimate_path(@task, fixed_cost)

app/views/tasks/new.html.haml
=render :partial => 'shared/project_nav', :locals => {:current => :tasks}

%h1 New task

= render 'form'

= link_to 'Back', project_tasks_path(@project)