config/routes.rb
Designbuild::Application.routes.draw do
  
  resources :resource_allocations

  resources :resource_requests

  resources :resources do
    resources :resource_allocations
  end

  resources :invoices do
    resources :invoice_lines
    resources :invoice_lines, :as => :line_items
    resources :invoice_markup_lines
    resources :invoice_markup_lines, :as => :markups
    
    member do
      get :start
      get :assign_costs
      get :set_amounts
      get :add_markups
      get :select_template
      get :finished
      
      get :accept_costs
      get :accept_markups
    end
  end  

  resources :payments do
    resources :payment_lines
    resources :payment_lines, :as => :line_items
    resources :payment_markup_lines
    resources :payment_markup_lines, :as => :markups

    member do
      get :start
      get :balance
      get :finished
      
      get :accept
    end
  end
    
  resources :milestones

  resources :suppliers
  
  resources :laborers  
  
  resources :projects do
    resources :components do
      member do
        get :changelog
        get :new_cost
        post :sort
      end
      collection do
        post :sort
      end
    end
    resources :tasks        # re-nested
    
    resources :contracts do
      collection do
        post :sort
      end
    end
        
    resources :invoices     # re-nested
    resources :payments     # re-nested
    
    resources :resource_requests
    
    member do
      post :add_markup, :as => :add_markup_to
      get :autocomplete_task_name
    end
    
    resources :markups do
      member do
        get :add, :action => :add_to_project
        get :remove, :action => :remove_from_project
      end
    end
    
    member do
      get :timeline, :as => :timeline_for
      get :estimate_report, :as => :estimate_report_for
      get :cost_report, :as => :cost_report_for
      get :purchase_order_list, :as => :purchase_order_list_for
      get :labor_summary, :as => :labor_summary_for
      get :payroll_summary, :as => :payroll_summary_for
      get :material_cost_summary, :as => :material_cost_summary_for
      get :invoicing
    end
    
    collection do
      get :purchase_order_list
      get :labor_summary
      get :payroll_summary
      get :material_cost_summary
    end
  end

  resources :components do
    resources :quantities
    resources :fixed_cost_estimates
    resources :unit_cost_estimates
    resources :contracts
    resources :markups
    resources :components, :as => :subcomponents, :path => :subcomponents
    
    member do
      post :add_markup, :as => :add_markup_to
      get :changelog
    end
    
    resources :markups, :only => [:new, :create, :edit, :update] do
      member do
        get :add, :action => :add_to_component
        get :remove, :action => :remove_from_component
      end
    end
  end
    
  resources :tasks do
    resources :labor_costs        # re-nested
    resources :material_costs     # re-nested

    member do
      post :add_markup, :as => :add_markup_to
      get :estimated_costs
      get :costs
    end
    
    resources :markups do
      member do
        get :add, :action => :add_to_task
        get :remove, :action => :remove_from_task
      end
    end
    
    resources :unit_cost_estimates do
      member do
        get :add, :action => :add_to_task
        get :remove, :action => :remove_from_task
      end
    end
    
    resources :fixed_cost_estimates do
      member do
        get :add, :action => :add_to_task
        get :remove, :action => :remove_from_task
      end
    end
  end
    
  resources :labor_costs do    
    resources :labor_cost_lines, :as => :line_items
    
    collection do
      get :overview
    end
  end
  
  resources :material_costs do
    resources :material_cost_lines, :as => :line_items
    get :autocomplete_supplier_name, :on => :collection
  end
  
  resources :contracts do
    resources :bids
    resources :contract_costs

    member do
      post :add_markup, :as => :add_markup_to
    end
    
    resources :markups do
      member do
        get :add, :action => :add_to_contract
        get :remove, :action => :remove_from_contract
      end
    end
  end

  resources :tags
  
  resources :markups
  
  namespace :admin do
    resources :users
  end
  
  devise_for :users
  
  
  match 'reports', :controller => :reports, :action => :index, :as => :reports
  match 'reports/:action', :controller => :reports
  

  root :to => "projects#index"
  

end

app/views/shared/_ajax_status.js.erb
jQuery(function($) {
  // create a convenient toggleLoading function
  var toggleLoading = function() { $("#loading").toggle() };

  $(document)
    .bind("ajax:loading",  function(){ $("#failure").hide(); $("#loading").show(); })
    .bind("ajax:failure", function(){ $("#loading").hide(); $("#failure").show(); })
    .bind("ajax:success", function(){ $("#loading").hide(); $("#failure").hide(); });
});

app/views/shared/_breadcrumbs.html.haml
-ancestors.each do |ancestor|
	=link_to ancestor.name, ancestor.class == Project ? ancestor : [@project, ancestor]
	>

app/views/shared/_project_nav.html.haml
-cache( @project.nil? ? "project_nav" : "project_nav_#{@project.id}" ) do
  -current ||= nil
  .main_nav
    -unless @project.nil?
      %ul.nav_left
        %li{:class => current == :dashboard ? :current : nil}
          =link_to @project.name, project_path(@project)
          -unless Project.count < 2
            .expander
              .activator=icon :expand_down
              .positioner
                %ul
                  -Project.all.each do |project|
                    %li.expand_active_area
                      .left=link_to project.name, project
                      
                &nbsp;

        %li{:class => current == :components ? :current : nil}
          = link_to 'Components', project_components_path(@project)
          -unless @project.components.empty?
            .expander
              .activator=icon :expand_down
              .positioner
                %ul
                  %li.expand_active_area
                    .left
                      %strong=link_to @project.name, @project
                    .right
                      %strong=number_to_currency @project.estimated_cost, :precision => 0
                  -recursion = Proc.new do |component,indent,block| 
                    %li.expand_active_area{:class => "indent_#{indent}"}
                      .left=link_to component.name, [@project, component]
                      .right= number_to_currency component.estimated_cost, :precision => 0  
                    -component.children.each do |child|
                      -block.call(child,indent+1,block)
                              
                  -@project.components.roots.each do |component|
                    -recursion.call(component, 0, recursion)
                    
                &nbsp;
                
        %li{:class => current == :contracts ? :current : nil}
          =link_to 'Contracts', project_contracts_path(@project)
          -unless @project.contracts.empty?
            .expander
              .activator=icon :expand_down
              .positioner
                %ul
                  -@project.contracts.each do |contract|
                    %li.expand_active_area
                      .left
                        =link_to contract.name, [@project, contract]
            
        %li{:class => current == :tasks ? :current : nil}
          = link_to 'Tasks', project_tasks_path(@project)
          -unless @project.tasks.empty?
            .expander
              .activator=icon :expand_down
              .positioner
                %ul
                  -@project.tasks.each do |task|
                    %li.expand_active_area
                      .left
                        =link_to task.name, [@project, task] 
                &nbsp;

        %li{:class => current == :invoicing ? :current : nil}
          = link_to 'Invoicing', invoicing_project_path(@project)
          
    -else
      %ul.nav_left
        %li{:class => current == :dashboard ? :current : nil}
          -unless Project.count < 2
            .expander
              .activator
                Project
                =icon :expand_down
              .positioner
                %ul
                  -Project.all.each do |project|
                    %li.expand_active_area
                      .left=link_to project.name, project
                      
                &nbsp;
                            
    %ul.nav_right
      %li{:class => current == :projects ? :current : nil}=link_to 'Home', projects_path
      %li{:class => current == :reports ? :current : nil}=link_to 'Reports', reports_path
      %li{:class => current == :resources ? :current : nil}
        =link_to 'Resources', resources_path
        .expander
          .activator=icon :expand_down
          .positioner
            %ul
              -Resource.all.each do |resource|
                %li.expand_active_area= link_to resource.name, resource_resource_allocations_path(resource)

            &nbsp;
      %li{:class => current == :labor ? :current : nil}=link_to 'Labor', overview_labor_costs_path
      /
        %li=link_to 'Log Out', destroy_user_session_path
   
  .main_nav_spacer

-if notice
  %p.notice= notice
-else
  %p.notice.hidden
-if alert
  %p.error.alert= alert
-else
  %p.alert.hidden
  
#failure.error.hidden
  =icon :exclamation
  Something went wrong!  Try <a href="#" onclick="location.reload();">reloading the page</a>
  
#loading.notice.hidden
  =image_tag 'spinner_small.gif'
  Working...

#post_errors

app/views/shared/_protovis_area_graph.js.erb
<%# 
  data = [{:value => 1.1, :label => 'blah'}] 
  width
  height
  min
  max
%>

<% xmin ||= data.map{|d| d[:x]}.compact.min * 0.8 %>
<% xmax ||= data.map{|d| d[:x]}.compact.max * 1.2 %>
<% ymin ||= data.map{|d| d[:y]}.compact.min * 0.8 %>
<% ymax ||= data.map{|d| d[:y]}.compact.max * 1.2 %>

var ag_data = <%= raw data.to_json %>;

var ag_w = <%= width %>,
    ag_h = <%= height %>,
    ag_max = <%= ymax %>,
    ag_min = <%= ymin %>,
    ag_idx = -1,
    ag_x = pv.Scale.linear(<%= xmin %>, <%= xmax %>).range(0,ag_w),
    ag_y = pv.Scale.linear(ag_min, ag_max).range(0,ag_h),
    ag_color = pv.Scale.linear(0, 75, 100).range('green', 'yellow', 'red');
    
var ag_vis = new pv.Panel()
    .def('i', -1)
    .width(ag_w)
    .height(ag_h)
    .events("all")
    .event("mousemove", pv.Behavior.point(Infinity).collapse("y"));
        
 
// Area graph
var ag_area = ag_vis.add(pv.Area)
    .data( ag_data )
    .segmented( true )
    .bottom(0)
    .height(function(d) ag_y(d['y']) )
    .left(function(d) ag_x(d['x']) )
    .fillStyle( 'rgba(255,165,0,.1)' )
    .event("point", function(d) ag_vis.i(this.index) )
    .event("unpoint", function() ag_vis.i(-1) );
    
// Top Line
ag_area.anchor('top').add(pv.Line)
    .strokeStyle('orange')
    .lineWidth(4);
    
// Points
ag_area.add(pv.Dot)
    .radius(5)
    .strokeStyle(null)
    .fillStyle( 'orange' )
    .left( function(d) ag_x(d['x']) )
    .bottom( function(d) ag_y(d['y']) )
    .visible( function() ag_vis.i() == this.index )
  .anchor('top').add(pv.Label)
    .text( function(d) d['label'] );

    
ag_vis.render();

app/views/shared/_protovis_line_graph.js.erb
<%# 
  data = [ { :name => 'one', :color => 'orange', :data => [{:value => 1.1, :label => 'blah'}] } ]
  width
  heighth
  min
  max
%>

<% xmin ||= data.map{|d| d[:data].map{|d| d[:x]}.compact.min }.compact.min * 0.8 %>
<% xmax ||= data.map{|d| d[:data].map{|d| d[:x]}.compact.min }.compact.max * 1.2 %>
<% ymin ||= multiply_or_nil data.map{|d| d[:data].map{|d| d[:y]}.compact.min }.compact.min, 0.8 %>
<% ymax ||= multiply_or_nil data.map{|d| d[:data].map{|d| d[:y]}.compact.max }.compact.max, 1.2 %>

var lg_data = <%= raw data.to_json %>;

var lg_w = <%= width %>,
    lg_h = <%= height %>,
    lg_max = <%= ymax %>,
    lg_min = <%= ymin %>,
    lg_x = pv.Scale.linear(<%= xmin %>, <%= xmax %>).range(0,lg_w);
    lg_y = pv.Scale.linear(lg_min, lg_max).range(0,lg_h);
    
var lg_vis = new pv.Panel()
    .def('i', -1)
    .width(lg_w)
    .height(lg_h)
    .events("all")
    .event("mousemove", pv.Behavior.point(Infinity).collapse("y"));
        
 
// Area graph
var lg_graph = lg_vis.add(pv.Panel)
    .data( lg_data );

    
// Lines
var lg_lines = lg_graph.add(pv.Panel)
    .def('color', function(d) d['color'] )
    .def('line', function(d) d['line'] )
  .add(pv.Line)
    .data( function(d) d['data'] )
    .bottom( function(d) lg_y( d['y'] ) )
    .left(function(d) lg_x( d['x'] ) )
    .lineWidth( function(d) this.parent.line() ? this.parent.line() : 4 )
    .strokeStyle( function() this.parent.color() )
    .event("point", function(d) lg_vis.i(this.index) )
    .event("unpoint", function() lg_vis.i(-1) );

// Points
var lg_points = lg_lines.add(pv.Dot)
    .radius(5)
    .strokeStyle(null)
    .fillStyle( function() this.parent.color() )
    .left( function(d) lg_x( d['x'] ) )
    .bottom( function(d) lg_y(d['y']) )
    .visible( function() lg_vis.i() == this.index );
    
// Labels
lg_points.anchor('top').add(pv.Label)
    .text( function(d) d['label'] );
 
lg_vis.render();

app/views/shared/_protovis_sparkbars.js.erb
<%# 
  data = [{:value => 1.1, :label => 'blah'}] 
  width
  height
  min
  max
%>

<% xmin ||= 0 %>
<% xmax ||= data.count %>
<% ymin ||= data.map{|d| d[:y]}.compact.min * 0.8 %>
<% ymax ||= data.map{|d| d[:y]}.compact.max * 1.2 %>
<% fill_style ||= 'rgba(255,165,0,.1)' %>
<% stroke_style ||= 'orange' %>

var ag_data = <%= raw data.to_json %>;

var ag_w = <%= width %>,
    ag_h = <%= height %>,
    ag_max = <%= ymax %>,
    ag_min = <%= ymin %>,
    ag_idx = -1,
    ag_x = pv.Scale.linear(<%= xmin %>, <%= xmax %>).range(0,ag_w),
    ag_y = pv.Scale.root(.01, ag_max).range(0,ag_h),
    ag_color = pv.Scale.linear(0, 75, 100).range('green', 'yellow', 'red');
    
var ag_vis = new pv.Panel()
    .def('i', -1)
    .width(ag_w)
    .height(ag_h);
        
 
// Area graph
var ag_area = ag_vis.add(pv.Bar)
    .data( ag_data )
    .segmented( true )
    .bottom(0)
    .height(function(d) ag_y(d['y']) )
    .left(function(d) ag_x(d['x']) )
    .width(function(d) ag_x(0.8))
    .fillStyle( '<%= fill_style %>' );
    
// Top Line
//ag_area.anchor('top').add(pv.Line)
//    .strokeStyle('<%= stroke_style %>')
//    .lineWidth(2);

ag_vis.render();

app/views/shared/_protovis_sparklines.js.erb
<%# 
  data = [{:value => 1.1, :label => 'blah'}] 
  width
  height
  min
  max
%>

<% xmin ||= data.map{|d| d[:x]}.compact.min * 0.8 %>
<% xmax ||= data.map{|d| d[:x]}.compact.max * 1.2 %>
<% ymin ||= data.map{|d| d[:y]}.compact.min * 0.8 %>
<% ymax ||= data.map{|d| d[:y]}.compact.max * 1.2 %>
<% fill_style ||= 'rgba(255,165,0,.1)' %>
<% stroke_style ||= 'orange' %>

var ag_data = <%= raw data.to_json %>;

var ag_w = <%= width %>,
    ag_h = <%= height %>,
    ag_max = <%= ymax %>,
    ag_min = <%= ymin %>,
    ag_idx = -1,
    ag_x = pv.Scale.linear(<%= xmin %>, <%= xmax %>).range(0,ag_w),
    ag_y = pv.Scale.linear(ag_min, ag_max).range(0,ag_h),
    ag_color = pv.Scale.linear(0, 75, 100).range('green', 'yellow', 'red');
    
var ag_vis = new pv.Panel()
    .def('i', -1)
    .width(ag_w)
    .height(ag_h);
        
 
// Area graph
var ag_area = ag_vis.add(pv.Area)
    .data( ag_data )
    .segmented( true )
    .bottom(0)
    .height(function(d) ag_y(d['y']) )
    .left(function(d) ag_x(d['x']) )
    .fillStyle( '<%= fill_style %>' );
    
// Top Line
ag_area.anchor('top').add(pv.Line)
    .strokeStyle('<%= stroke_style %>')
    .lineWidth(2);

ag_vis.render();

app/views/shared/_protovis_timeline.js.erb
<% tasks ||= @project.tasks %>
<% start_date = LaborCost.by_project(@project).order(:date).first.date %>
<% data = tasks.all(:order => 'percent_complete DESC').map do |task| %>
  <% {
    :task_name => "#{task.name} #{number_to_percentage task.percent_complete, :precision => 0} est, #{number_to_percentage( task.percent_of_estimated || 0, :precision => 0)} spent", 
    :task_start => task.labor_costs.empty? ? Date::today - start_date : task.labor_costs.last.date - start_date,
    :task_end => (task.is_complete? && !task.labor_costs.empty? ? task.labor_costs.first.date : Date::today) - start_date,
    :labor_costs => task.labor_costs.all.reverse.map{ |lc| 
      {:id => lc.id,
      :percent_complete => lc.percent_complete,
      :percent_of_estimated => lc.task.version_at(lc.date).nil? || lc.task.version_at(lc.date).percent_of_estimated.nil? ? lc.percent_complete : lc.task.version_at(lc.date).percent_of_estimated,
      :label => lc.task.version_at(lc.date).nil? || lc.task.version_at(lc.date).percent_of_estimated.nil? ? "#{number_to_percentage lc.percent_complete, :precision => 0} complete" : "#{number_to_percentage lc.percent_complete, :precision => 0} complete, #{number_to_percentage lc.task.version_at(lc.date).percent_of_estimated, :precision => 0} of est.", 
      :date => lc.date - start_date }
    }
    } %>
<% end %>
<% weeks = (0..60).to_a.reverse.map{|week| day = weekday(1, (week-4).weeks.ago.to_date ); {:name => day.strftime('%b %d'), :value => day - start_date}} %>


var scale = <%= Date::today == start_date ? 1 : 400/(Date::today - start_date) %>;
var data = <%= raw data.to_json %>;
var weeks = <%= raw weeks.to_json %>;
var rangeStart = <%= Date::today - start_date > 60 ? (Date::today - start_date) - 60 : Date::today - start_date %>;
var rangeEnd = <%= (Date::today - start_date) + 7 %>;

var w = <%= width %>,
    h = <%= height %>,
    x = pv.Scale.linear(rangeStart, rangeEnd).range(0, w/1.25);
    y = pv.Scale.linear(0, <%= tasks.count %>).range(0, <%= tasks.count %> * 25);
    ww = pv.Scale.linear(0, (rangeEnd - rangeStart)).range(0, w/1.25);
    color = pv.Scale.linear(0, 75, 100).range('green', 'yellow', 'red');
    
vis = new pv.Panel()
    .def('hover', [-1,-1])
    .width(w)
    .height(h);
        
 
// Week Highlighting
var weeks = vis.add(pv.Bar)
    .data( weeks )
    .top(0)
    .bottom(0)
    .width( function(d) ww(5) )
    .left( function(d) x(d['value']) )
    .fillStyle(pv.color('rgba(0,0,0,.05)') );
    

// Task bars
var tasks = vis.add(pv.Bar)
    .data(data)
    .height(20)
    .top( function() y( this.index ) )
    .width( function(d) x(d['task_end']) - x(d['task_start']) )
    .left( function(d) x(d['task_start']) - 1  )
    .fillStyle( pv.color('rgba(0,0,0,.1)') );

  
// Pan/zoom panel 
vis.add(pv.Panel)
    .events("all")
    .event("mousedown", pv.Behavior.pan())
    .event("mousewheel", pv.Behavior.zoom())
    .event("pan", transform)
    .event("zoom", transform);
    
    
// Labor stripes
var labor = vis.add(pv.Panel)
    .data(data);
var labor_bars = labor.add(pv.Bar)
    .data( function(d) d['labor_costs'] )
    .height(8)
    .top( function() y(labor.index) + 1 )
    .width( function(d) ww(1)-2 )
    .left( function(d) x(d['date']) )
    .fillStyle( function(d) color( d['percent_complete'] ) )
    .event('mouseover', function(d) vis.hover( ['labor', d['id']] ) )
    .event('mouseout', function(d) vis.hover( [-1,-1] ) )
  .add(pv.Bar)
    .top( function() y(labor.index) + 10 )
    .fillStyle( function(d) color( d['percent_of_estimated'] ) )
    .event('mouseover', function(d) vis.hover( ['labor', d['id']] ) )
    .event('mouseout', function(d) vis.hover( [-1,-1] ) );


// Labels
tasks.anchor('right').add(pv.Label)
    .textAlign('left')
    .text(function(d) d['task_name']);
weeks.anchor('bottom').add(pv.Label)
    .text( function(d) d['name'] );
labor_bars.anchor('top').add(pv.Label)
    .text( function(d) d['label'] )
    .textBaseline('bottom')
    .visible( function(d) vis.hover()[0] == 'labor' && vis.hover()[1] == d['id'] );      
    
function transform() {
  var t = this.transform().invert();
  var k = Math.pow(t.k, 20);
  
  var xspan = rangeEnd - rangeStart;
  
  var xlow = rangeEnd-(xspan*k)+(t.x*(xspan/w*k));
  var xhigh = rangeEnd+(t.x*(xspan/w*k));
  
  x.domain( xlow, xhigh );
  ww.domain( 0, (xhigh - xlow) );
  
  y.range( -t.y, <%= tasks.count %> * 25 - t.y);
  vis.render();
}

vis.render();

app/views/shared/_qtips.js.erb
$(document).ready( function() {
  $('.qtip_component').qtip({
     content: '<p>Building Components provide a way to organize your design to simplify cost estimation.</p><p>Components can be nested in other components, and each component can be assigned a set ofquantities (describing things like floor area), unit costs (which allow you to specify a unitcost and inherit a value from quantities) and fixed costs (which are just a number)</p>',
     show: {delay: 1000},
     position: {
        corner: {
           target: 'topLeft',
           tooltip: 'topRight'
        }
     }
  });
  
  $('.qtip_task').qtip({
     content: '<p>Construction Tasks provide a way to organize the construction process so you can keep track of costs</p><p>Tasks can be associated with estimated costs so you can keep track of how much construction costs relative to your estimate.</p><p>You can keep track of construction costs for a given task by logging time spent on the task, or by keeping track of material costs</p>',
     show: {delay: 1000},
     position: {
        corner: {
           target: 'topLeft',
           tooltip: 'topRight'
        }
     }
  });
  
  $('.qtip_contract').qtip({
     content: '<p>Fixed-Bid Contracts provide a way to keep track of subcontractors.</p><p>You can keep track of multiple bids for a given contract, then choose which will be the "active" bid and keep track of invoices from that contractor.',
     show: {delay: 1000},
     position: {
        corner: {
           target: 'topLeft',
           tooltip: 'topRight'
        }
     }
  });
     
   $('.qtip_net').qtip({
      content: '<p>The difference between the estimated cost (including markup) and the projected cost (without markup)</p>',
      show: {delay: 1000},
      position: {
         corner: {
            target: 'topLeft',
            tooltip: 'topRight'
         }
      }
    });
         
    $('.qtip_projected').qtip({
       content: "<p>If a task is finished, the amount spent on the task.  If a task hasn't started, the estimated cost.  Otherwise, the greater of the estimated cost and cost to date</p>",
       show: {delay: 1000},
       position: {
          corner: {
             target: 'topLeft',
             tooltip: 'topRight'
          }
       }
    });
});