config/routes.rb
Designbuild::Application.routes.draw do
  
  resources :resource_allocations

  resources :resource_requests

  resources :resources do
    resources :resource_allocations
  end

  resources :invoices do
    resources :invoice_lines
    resources :invoice_lines, :as => :line_items
    resources :invoice_markup_lines
    resources :invoice_markup_lines, :as => :markups
    
    member do
      get :start
      get :assign_costs
      get :set_amounts
      get :add_markups
      get :select_template
      get :finished
      
      get :accept_costs
      get :accept_markups
    end
  end  

  resources :payments do
    resources :payment_lines
    resources :payment_lines, :as => :line_items
    resources :payment_markup_lines
    resources :payment_markup_lines, :as => :markups

    member do
      get :start
      get :balance
      get :finished
      
      get :accept
    end
  end
    
  resources :milestones

  resources :suppliers
  
  resources :laborers  
  
  resources :projects do
    resources :components do
      member do
        get :changelog
        get :new_cost
        post :sort
      end
      collection do
        post :sort
      end
    end
    resources :tasks        # re-nested
    
    resources :contracts do
      collection do
        post :sort
      end
    end
        
    resources :invoices     # re-nested
    resources :payments     # re-nested
    
    resources :resource_requests
    
    member do
      post :add_markup, :as => :add_markup_to
      get :autocomplete_task_name
    end
    
    resources :markups do
      member do
        get :add, :action => :add_to_project
        get :remove, :action => :remove_from_project
      end
    end
    
    member do
      get :timeline, :as => :timeline_for
      get :estimate_report, :as => :estimate_report_for
      get :cost_report, :as => :cost_report_for
      get :purchase_order_list, :as => :purchase_order_list_for
      get :labor_summary, :as => :labor_summary_for
      get :payroll_summary, :as => :payroll_summary_for
      get :material_cost_summary, :as => :material_cost_summary_for
      get :invoicing
    end
    
    collection do
      get :purchase_order_list
      get :labor_summary
      get :payroll_summary
      get :material_cost_summary
    end
  end

  resources :components do
    resources :quantities
    resources :fixed_cost_estimates
    resources :unit_cost_estimates
    resources :contracts
    resources :markups
    resources :components, :as => :subcomponents, :path => :subcomponents
    
    member do
      post :add_markup, :as => :add_markup_to
      get :changelog
    end
    
    resources :markups, :only => [:new, :create, :edit, :update] do
      member do
        get :add, :action => :add_to_component
        get :remove, :action => :remove_from_component
      end
    end
  end
    
  resources :tasks do
    resources :labor_costs        # re-nested
    resources :material_costs     # re-nested

    member do
      post :add_markup, :as => :add_markup_to
      get :estimated_costs
      get :costs
    end
    
    resources :markups do
      member do
        get :add, :action => :add_to_task
        get :remove, :action => :remove_from_task
      end
    end
    
    resources :unit_cost_estimates do
      member do
        get :add, :action => :add_to_task
        get :remove, :action => :remove_from_task
      end
    end
    
    resources :fixed_cost_estimates do
      member do
        get :add, :action => :add_to_task
        get :remove, :action => :remove_from_task
      end
    end
  end
    
  resources :labor_costs do    
    resources :labor_cost_lines, :as => :line_items
    
    collection do
      get :overview
    end
  end
  
  resources :material_costs do
    resources :material_cost_lines, :as => :line_items
    get :autocomplete_supplier_name, :on => :collection
  end
  
  resources :contracts do
    resources :bids
    resources :contract_costs

    member do
      post :add_markup, :as => :add_markup_to
    end
    
    resources :markups do
      member do
        get :add, :action => :add_to_contract
        get :remove, :action => :remove_from_contract
      end
    end
  end

  resources :tags
  
  resources :markups
  
  namespace :admin do
    resources :users
  end
  
  devise_for :users
  
  
  match 'reports', :controller => :reports, :action => :index, :as => :reports
  match 'reports/:action', :controller => :reports
  

  root :to => "projects#index"
  

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  autocomplete :task, :name, :full => true
  
  def invoicing
    @project = Project.find(params[:id])
    @invoices = @project.invoices
    @payments = @project.payments
    
    respond_to do |format|
      format.html
    end    
  end
  
  def timeline
    @project = Project.find(params[:id])
    
    respond_to do |format|
      format.html
    end      
  end
  
  def autocomplete_task_name
    object = :task
    method = :name
    options = {:full => true}
    
    @project = Project.find(params[:id])
    term = params[:term]

    if term && !term.empty?
      items = @project.tasks.where(["LOWER(name) LIKE ?", "%#{term.downcase}%"]).limit(10).order(:name)
    else
      items = {}
    end

    render :json => json_for_autocomplete(items, options[:display_value] ||= method)
  end

  def payroll_summary
    if params.has_key?(:id)
      @project = Project.find(params[:id])
      @labor_costs = LaborCost.by_project(@project)
    else
      @projects = Project.scoped
      @labor_costs = LaborCost.scoped
    end
    
    if params.has_key? :date
      @date = Date::new(params[:date][:year].to_i, params[:date][:month].to_i, params[:date][:day].to_i)
    else
      @date = Date::today
    end
    
    respond_to do |format|
      format.html
    end    
  end
    
  def labor_summary
    if params.has_key?(:id)
      @project = Project.find(params[:id])
      @tasks = @project.tasks
    else
      @projects = Project.scoped
      @tasks = Task.scoped
    end
    
    if params.has_key? :date
      begin
        @date = Date::new(params[:date][:year].to_i, params[:date][:month].to_i, params[:date][:day].to_i)
      rescue ArgumentError
        @date = Date::today
        flash[:alert] = "Date Error: Check that the date you entered (#{params[:date][:month]}/#{params[:date][:day]}/#{params[:date][:year]}) actually exists..."
      end
    else
      @date = Date::today
    end
    
    respond_to do |format|
      format.html
    end    
  end

  def material_cost_summary
    if params.has_key?(:id)
      @project = Project.find(params[:id])
      @tasks = @project.tasks
    else
      @projects = Project.scoped
      @tasks = Task.includes(:project) & @projects
    end
    
    if params.has_key? :date
      begin
        @date = Date::new(params[:date][:year].to_i, params[:date][:month].to_i, params[:date][:day].to_i)
      rescue ArgumentError
        @date = Date::today
        flash[:alert] = "Date Error: Check that the date you entered (#{params[:date][:month]}/#{params[:date][:day]}/#{params[:date][:year]}) actually exists..."
      end
    else
      @date = Date::today
    end
    
    respond_to do |format|
      format.html
    end    
  end
    
  def purchase_order_list
    if params.has_key?(:id)
      @projects = [Project.find(params[:id])]
    else
      @projects = Project.all
    end
    @suppliers = Supplier.all
    
    respond_to do |format|
      format.html
    end
  end
  
  def add_markup
    @project = Project.find(params[:id])
    
    respond_to do |format|
      if @project.markups << Markup.find(params[:markup_id])
        format.html { redirect_to(@project, :notice => 'Markup was successfully added.') }
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def estimate_report
    @project = Project.find(params[:id])
    session[:break_out_unit_costs] = (1 == params[:break_out_unit_costs].to_i) if params.has_key?(:break_out_unit_costs)
    session[:break_out_markup] = (1 == params[:break_out_markup].to_i) if params.has_key?(:break_out_markup)
    session[:show_graph] = (1 == params[:show_graph].to_i) if params.has_key?(:show_graph)

    respond_to do |format|
      format.html # show.html.erb
    end  
  end

  def cost_report
    @project = Project.find(params[:id])
    session[:break_out_costs] = (1 == params[:break_out_costs].to_i) if params.has_key?(:break_out_costs)

    respond_to do |format|
      format.html # show.html.erb
    end  
  end
    
  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.order( :name ).all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])
    @inactive_markups = Markup.scoped - @project.markups

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new

    respond_to do |format|
      format.js
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.js {
          @projects = Project.order( :name ).all
        }
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.js
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.js {
          @projects = Project.order( :name ).all
        }
        format.html { redirect_from_session_or(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.js
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_cost_report.html.haml
-unless component.estimated_cost.nil?
  %tr
    %td.control
      -unless component.children.empty?
        =form_for( [@project, component], :html => { :id => "expand_#{component.id}" } ) do |f|
          =f.check_box :expand_in_estimate, :onchange => "$('form#expand_#{component.id}').submit();"
          =hidden_field_tag :redirect, estimate_report_for_project_path(@project)
        
    %td{:class => (indent == 0 ? nil : "indent_#{indent}" )}  
      %strong= component.name if indent == 0
      = component.name unless indent == 0
      
    -if session[:break_out_costs]
      %td.currency
      %td.boolean.control
      
    %td.currency
      %strong= number_to_currency component.cost if indent == 0
      = number_to_currency component.cost unless indent == 0
      
    %td.currency
      %strong= number_to_currency component.estimated_raw_cost if indent == 0
      = number_to_currency component.estimated_raw_cost unless indent == 0
        
    -if session[:break_out_costs]
      -component.labor_costs.reorder(:date).each do |labor_cost|
        %tr
          %td.control
          %td{:class => "indent_#{indent+1}"}
            %i= "#{labor_cost.date.to_s(:long)}: #{labor_cost.task.name} Labor"
          %td
            %i= number_to_currency labor_cost.raw_cost
          %td.control
            =form_for labor_cost, :remote => true do |f|
              =hidden_field_tag :render_nothing, true
              =f.check_box :reconciled, {:onchange => "$(this.form).submit();"}
          %td
          %td
        
      -component.material_costs.reorder(:date).each do |material_cost|
        %tr
          %td.control
          %td{:class => "indent_#{indent+1}"}
            %i= "#{material_cost.date.to_s(:long)}: #{material_cost.task.name} Material from #{material_cost.supplier.name}"
          %td
            %i= number_to_currency material_cost.raw_cost
          %td.control
            =form_for material_cost, :remote => true do |f|
              =hidden_field_tag :render_nothing, true
              =f.check_box :reconciled, {:onchange => "$(this.form).submit();"}
          %td
          %td
        
      -component.contracts.each do |contract|
        -contract.costs.reorder(:date).each do |contract_cost|
          %tr
            %td.control
            %td{:class => "indent_#{indent+1}"}
              %i= "#{contract_cost.date.to_s(:long)}: #{contract.name} Invoice from #{contract.active_bid.contractor}"
            %td
              %i= number_to_currency contract_cost.raw_cost
            %td.control
              =form_for [contract, contract_cost], :remote => true do |f|
                =hidden_field_tag :render_nothing, true
                =f.check_box :reconciled, {:onchange => "$(this.form).submit();"}
            %td       
            %td 
          
        
  -if component.expand_in_estimate
    -component.children.each do |subcomponent|
      =render :partial => 'cost_report', :locals => {:component => subcomponent, :indent => indent + 1}

app/views/projects/_estimate_report_component.html.haml
-unless component.estimated_cost.nil?
  %tr
    %td.control
      -unless component.children.empty?
        =form_for( [@project, component], :html => { :id => "expand_#{component.id}" } ) do |f|
          =f.check_box :expand_in_estimate, :onchange => "$('form#expand_#{component.id}').submit();"
          =hidden_field_tag :redirect, estimate_report_for_project_path(@project)
    %td.control
      -unless component.fixed_cost_estimates.empty? && component.unit_cost_estimates.empty? && component.contracts.empty?
        =form_for( [@project, component], :html => { :id => "costs_#{component.id}" } ) do |f|
          =f.check_box :show_costs_in_estimate, :onchange => "$('form#costs_#{component.id}').submit();"
          =hidden_field_tag :redirect, estimate_report_for_project_path(@project)
        
    %td{:class => (indent == 0 ? nil : "indent_#{indent}" )}  
      %strong= component.name if indent == 0
      = component.name unless indent == 0
      
    -if session[:break_out_unit_costs]
      %td
      %td.currency
    -elsif session[:show_graph]
      %td.sparklines
        -prior = component.estimated_cost_points.where('date <= ?', Date::today - 30)
        -if prior.empty?
          -data = []
        -else
          -data = [ {:x => (prior.last.date - Date::today + 30), :y => prior.last.value } ]
          
        -data += component.estimated_cost_points.where('date > ?', Date::today - 30).all.map{|d| {:x => (d.date - Date::today + 30), :y => d.value} }

        -data.push( {:x => 30, :y => component.estimated_cost} )
        
        -unless data.empty?
          %script{:type => 'text/javascript+protovis'}
            = render :partial => 'shared/protovis_sparklines.js', :locals => { :data => data, :width => 150, :height => 20, :xmin => 0, :xmax => 30, :fill_style => 'rgb(220,220,220)', :stroke_style => 'black' } 
          
    -if session[:break_out_markup]
      %td.currency
        %strong= number_to_currency component.estimated_raw_cost if indent == 0
        = number_to_currency component.estimated_raw_cost unless indent == 0
    -else
      %td.currency
        %strong= number_to_currency component.estimated_cost if indent == 0
        = number_to_currency component.estimated_cost unless indent == 0
      
  -if component.show_costs_in_estimate
    -component.unit_cost_estimates.each do |unit_cost|
      %tr
        %td.control
        %td.control
        %td{:class => "indent_#{indent+1}"}
          %i= unit_cost.name
        -if session[:break_out_unit_costs]
          %td
            ="#{unit_cost.quantity.value.to_i} #{unit_cost.quantity.unit} +#{number_to_percentage unit_cost.drop, :precision => 0} (#{unit_cost.quantity.name})" unless unit_cost.drop.nil?
            ="#{unit_cost.quantity.value.to_i} #{unit_cost.quantity.unit} (#{unit_cost.quantity.name})" if unit_cost.drop.nil?
          %td="#{number_to_currency unit_cost.unit_cost}/#{unit_cost.quantity.unit.singularize}"
        -elsif session[:show_graph]
          %td
          
        -if session[:break_out_markup]
          %td.currency
            %i= number_to_currency unit_cost.raw_cost
        -else
          %td.currency
            %i= number_to_currency unit_cost.cost
      
    -component.fixed_cost_estimates.each do |fixed_cost|
      %tr
        %td.control
        %td.control
        %td{:class => "indent_#{indent+1}"}
          %i= fixed_cost.name
        -if session[:break_out_unit_costs]
          %td
          %td.currency
        -elsif session[:show_graph]
          %td.sparklines
          
        -if session[:break_out_markup]
          %td.currency
            %i= number_to_currency fixed_cost.raw_cost
        -else
          %td.currency
            %i= number_to_currency fixed_cost.cost
          
    -component.contracts.each do |contract|
      =render :partial => 'estimate_report_contract', :locals => {:contract => contract, :indent => indent+1}
      
  -if component.expand_in_estimate
    -component.children.each do |subcomponent|
      =render :partial => 'estimate_report_component', :locals => {:component => subcomponent, :indent => indent + 1}

app/views/projects/_project_list.html.haml
%table.projects
  %tr
    %th Name
    %th.currency Cost Estimate
    %th.currency Cost-to-Date
    %th 
    %th
    %th
    %th
    %th.control
    %th.control

  - @projects.each do |project|
    %tr{:id => "project_#{project.id}"}
      %td= link_to project.name, project
      %td.currency= number_to_currency(project.estimated_cost)
      %td.currency= number_to_currency(project.cost)
      %td.control= link_to 'Components', project_components_path(project)
      %td.control= link_to 'Tasks', project_tasks_path(project)
      %td.control= link_to 'Contracts', project_contracts_path(project)
      %td.control.edit= link_to 'Rename', edit_project_path(project), :remote => true
      %td.control.destroy= link_to icon(:delete), project, :confirm => 'Are you sure?', :method => :delete
      
  - if @projects.empty?
    %tr
      %td{:colspan => 10} (None)
      
  %tr.control.add_button
    %td{:colspan => 10}
      = link_to new_project_path, :remote => true do
        = icon(:add)
        Add Project

app/views/projects/_projected_vs_estimated.html.haml
#projected_vs_estimated_cost
  (pretty graph here)

app/views/projects/create.js.erb
<% if @project.errors.any? %>
  //Error
  
  <% content_for :error_tr do %>
    <tr class='error'><td colspan = 10><strong><%= error_messages_for(@project) %></strong></td></tr>
  <% end %>

  //Hide the flash notice div
  $("#flash_notice").hide(300);

  //Add a table row above the input with error info
  $("table.projects tr.error").remove();
  $("table.projects tr.project_fields").before("<%= escape_javascript( yield :error_tr ) %>");

<% else %>
  //Success
  
  <% content_for :table do %>
  	<%=render :partial => 'project_list', :locals => {:projects => @projects} %>
  <% end %>

  //Update the html of the div flash_notice with the new one
  $("#flash_notice").html("<%= escape_javascript(flash[:notice])%>");

  //Show the flash_notice div
  $("#flash_notice").show(300);

  //Replace the html of the div post_lists with the updated new one
  $('form.new_project').html( "<%= escape_javascript( yield :table ) %>");

  //Remove the form
  $('table.projects').unwrap();
  
  //Load a new entry field
  //$('table.projects tr.add_button > td > a').click();
  
<% end %>

app/views/projects/index.html.haml
=render :partial => 'shared/project_nav', :locals => {:current => :projects}

.container
  %h1 Projects

  .main_actions
    View:
    =link_to 'Employees', laborers_path
    =link_to 'Users', admin_users_path
    
  %hr

  =render :partial => 'project_list'

app/views/projects/show.html.haml
-content_for :head do
  =javascript_include_tag "autocomplete-rails.js"
  =javascript_include_tag "jquery.dimscreen.js"
  =stylesheet_link_tag 'jquery.theme.css', :media => 'screen, projection'
  =javascript_include_tag 'protovis-d3.2.js'
  
=render :partial => 'shared/project_nav', :locals => {:current => :dashboard}

.container
  =render :partial => 'nav', :locals => {:current => :dashboard}

  .header
    %h2
      Planning Dashboard
      -if @project.show_planning
        .control.inline
          =form_for @project do |f|
            =f.hidden_field :show_planning, :value => false
            =f.submit 'Hide'
      -else
        .control.inline
          =form_for @project do |f|
            =f.hidden_field :show_planning, :value => true
            =f.submit 'Show'
                        
  
  -if @project.show_planning
    .left
      -cache(:action_suffix => 'est_graph', :expires_in => 1.day) do
        -unless @project.estimated_cost_points.empty?
          %h3 Estimated Cost Graph
          .boxed
            %script{:type => 'text/javascript+protovis'}
              / Includes the last point prior to the date range and the current value
              -if @project.estimated_cost_points.where('date < ?', 30.days.ago).empty?
                =data = []
              -else
                -data = [ @project.estimated_cost_points.where('date < ?', 30.days.ago).last ].map {|d| {:x => (d.date - 30.days.ago.to_date), :y => d.value, :label => "#{d.date.strftime('%b %d')}: #{number_to_currency d.value, :precision => 0}"} }
              -data += @project.estimated_cost_points.where('date > ?', 30.days.ago).all.map {|d| {:x => (d.date - 30.days.ago.to_date), :y => d.value, :label => "#{d.date.strftime('%b %d')}: #{number_to_currency d.value, :precision => 0}"} }
              -data += [ {:x => 30, :y => @project.estimated_cost, :label => "#{Date.today.strftime('%b %d')}: #{number_to_currency @project.estimated_cost, :precision => 0}"} ]
              -unless data.empty?
                =render :partial => 'shared/protovis_area_graph.js', :locals => {:height => 120, :width => 490, :data => data, :xmin => 0, :xmax => 30, :ymin => 0}
        
      .right
        =link_to estimate_report_for_project_path(@project) do
          %button Project Cost Estimate
          
    .left
      %h3 Unassigned Unit Costs
      .boxed=render :partial => 'unit_cost_estimates/unassigned', :locals => {:unit_cost_estimates => @project.unit_cost_estimates.unassigned,}
    .right
      %h3 Unassigned Fixed Costs
      .boxed=render :partial => 'fixed_cost_estimates/unassigned', :locals => {:fixed_cost_estimates => @project.fixed_cost_estimates.unassigned}

  %hr

  .header
    %h2 
      Construction Dashboard
      -if @project.show_construction
        .control.inline
          =form_for @project do |f|
            =f.hidden_field :show_construction, :value => false
            =f.submit 'Hide'
      -else
        .control.inline
          =form_for @project do |f|
            =f.hidden_field :show_construction, :value => true
            =f.submit 'Show'
            
  -if @project.show_construction    
    .right
      =link_to cost_report_for_project_path(@project) do
        %button Project Cost Summary

    .full_width
      %h3 Task Summary
      =render :partial => 'tasks/summary'
      
      -thursday = weekday(4,Date::today)
      =link_to labor_summary_for_project_path(@project, 'date[year]' => thursday.year, 'date[month]' => thursday.month, 'date[day]' => thursday.day) do
        %button This Week's Labor Summary     
      =link_to payroll_summary_for_project_path(@project, 'date[year]' => thursday.year, 'date[month]' => thursday.month, 'date[day]' => thursday.day) do
        %button This Week's Payroll Summary
      =link_to material_cost_summary_for_project_path(@project, 'date[year]' => thursday.year, 'date[month]' => thursday.month, 'date[day]' => thursday.day) do
        %button This Week's Material Cost Summary
    
    -unless LaborCost.where('project_id = ?', @project.id).empty?
      .full_width
        -cache(:action_suffix => 'labor_allocation_graph', :expires_in => 1.hour) do
          %h3 Labor Allocation Timeline
          %script{:type => 'text/javascript+protovis'}
            -tasks = @project.tasks.active.empty? ? @project.tasks : @project.tasks.active
            =render :partial => 'shared/protovis_timeline.js', :locals => {:height => 150, :width => 990, :tasks => tasks}

          .right
            =link_to timeline_for_project_path(@project) do
              %button View Larger
            
    .full_width
      -cache(:action_suffix => 'proj_vs_est_graph', :expires_in => 1.day) do
        %h3 Projected vs Estimated Cost
        %script{:type => 'text/javascript+protovis'}
        
          -estimated = ( [@project.estimated_cost_points.where('date < ?', 56.days.ago).last] + @project.estimated_cost_points.where('date > ?', 56.days.ago).all ).compact.map {|d| {:x => (d.date - 56.days.ago.to_date), :y => d.value, :label => "Estimate: #{number_to_currency(d.value, :precision => 0)}" } }
          -estimated += [{:x => 56, :y => @project.estimated_cost, :label => "Estimate: #{number_to_currency(@project.estimated_cost, :precision => 0)}" }]
          -projected = ( [@project.projected_cost_points.where('date < ?', 56.days.ago).last] + @project.projected_cost_points.where('date > ?', 56.days.ago).all ).compact.map {|d| {:x => (d.date - 56.days.ago.to_date), :y => d.value, :label => "Projected: #{number_to_currency(d.value, :precision => 0)}" } }
          -projected += [{:x => 56, :y => @project.projected_cost, :label => "Projected: #{number_to_currency(@project.projected_cost, :precision => 0)}" }]
          -actual = ( [@project.cost_to_date_points.where('date < ?', 56.days.ago).last] + @project.cost_to_date_points.where('date > ?', 56.days.ago).all ).compact.map {|d| {:x => (d.date - 56.days.ago.to_date), :y => d.value, :label => "To Date: #{number_to_currency(d.value, :precision => 0)}" } }                  
          -actual += [{:x => 56, :y => @project.cost, :label => "To Date: #{number_to_currency(@project.cost, :precision => 0)}" }]

          -data = [ |
            {:name => 'Cost to Date', :color => 'hsl(0,0,75)', :line => '2', :data => actual}, |
            {:name => 'Projected Cost', :color => 'red', :data => projected}, |
            {:name => 'Estimated Cost', :color => 'orange', :data => estimated} |
          ] |
          =render :partial => 'shared/protovis_line_graph.js', :locals => {:height => 180, :width => 990, :data => data, :xmin => 0, :xmax => 56, :ymin => 0}
      
    .right
      %h3
        Currently Invoicing Contracts
      .boxed=render :partial => 'contracts/currently_invoicing'

    .right
      %h3 Current Purchase Orders
      .boxed=render :partial => 'material_costs/purchase_orders'
      
      .right
        =link_to purchase_order_list_for_project_path(@project) do
          %button Project Purchase Orders
        =link_to purchase_order_list_projects_path do
          %button All Purchase Orders
          
    .full_width
      %h3 Costs with ambiguous components
      
      %table
        %tr
          %th.date Date
          %th Task
          %th Note
          %th.currency Cost
          %th
          
        -@project.labor_costs.where(:component_id => nil).reorder(:date).each do |cost|
          %tr
            %td.date= cost.date.to_s(:long)
            %td= cost.task.name
            %td= cost.note
            %td.currency= number_to_currency cost.raw_cost
            %td
              =form_for [cost.task, cost], :remote => true do |f|
                =f.collection_select :component_id, @project.component_tree, :id, :select_label, {:include_blank => '--- Choose Component ---'}, {:onchange => "$(this.form).submit();"}

        -@project.material_costs.where(:component_id => nil).reorder(:date).each do |cost|
          %tr
            %td.date= cost.date.to_s(:long)
            %td= cost.task.name
            %td= "#{cost.note} @ #{cost.supplier.name}"
            %td.currency= number_to_currency cost.raw_cost
            %td
              =form_for [cost.task, cost], :remote => true do |f|
                =f.collection_select :component_id, @project.component_tree, :id, :select_label, {:include_blank => '--- Choose Component ---'}, {:onchange => "$(this.form).submit();"}

app/views/projects/timeline.html.haml
-content_for :head do
  =javascript_include_tag 'protovis-d3.2.js'

%script{:type => 'text/javascript+protovis'}
  =render :partial => 'shared/protovis_timeline.js', :locals => {:height => 500, :width => 990}