config/routes.rb
Designbuild::Application.routes.draw do
  
  resources :resource_allocations

  resources :resource_requests

  resources :resources do
    resources :resource_allocations
  end

  resources :invoices do
    resources :invoice_lines
    resources :invoice_lines, :as => :line_items
    resources :invoice_markup_lines
    resources :invoice_markup_lines, :as => :markups
    
    member do
      get :start
      get :assign_costs
      get :set_amounts
      get :add_markups
      get :select_template
      get :finished
      
      get :accept_costs
      get :accept_markups
    end
  end  

  resources :payments do
    resources :payment_lines
    resources :payment_lines, :as => :line_items
    resources :payment_markup_lines
    resources :payment_markup_lines, :as => :markups

    member do
      get :start
      get :balance
      get :finished
      
      get :accept
    end
  end
    
  resources :milestones

  resources :suppliers
  
  resources :laborers  
  
  resources :projects do
    resources :components do
      member do
        get :changelog
        get :new_cost
        post :sort
      end
      collection do
        post :sort
      end
    end
    resources :tasks        # re-nested
    
    resources :contracts do
      collection do
        post :sort
      end
    end
        
    resources :invoices     # re-nested
    resources :payments     # re-nested
    
    resources :resource_requests
    
    member do
      post :add_markup, :as => :add_markup_to
      get :autocomplete_task_name
    end
    
    resources :markups do
      member do
        get :add, :action => :add_to_project
        get :remove, :action => :remove_from_project
      end
    end
    
    member do
      get :timeline, :as => :timeline_for
      get :estimate_report, :as => :estimate_report_for
      get :cost_report, :as => :cost_report_for
      get :purchase_order_list, :as => :purchase_order_list_for
      get :labor_summary, :as => :labor_summary_for
      get :payroll_summary, :as => :payroll_summary_for
      get :material_cost_summary, :as => :material_cost_summary_for
      get :invoicing
    end
    
    collection do
      get :purchase_order_list
      get :labor_summary
      get :payroll_summary
      get :material_cost_summary
    end
  end

  resources :components do
    resources :quantities
    resources :fixed_cost_estimates
    resources :unit_cost_estimates
    resources :contracts
    resources :markups
    resources :components, :as => :subcomponents, :path => :subcomponents
    
    member do
      post :add_markup, :as => :add_markup_to
      get :changelog
    end
    
    resources :markups, :only => [:new, :create, :edit, :update] do
      member do
        get :add, :action => :add_to_component
        get :remove, :action => :remove_from_component
      end
    end
  end
    
  resources :tasks do
    resources :labor_costs        # re-nested
    resources :material_costs     # re-nested

    member do
      post :add_markup, :as => :add_markup_to
      get :estimated_costs
      get :costs
    end
    
    resources :markups do
      member do
        get :add, :action => :add_to_task
        get :remove, :action => :remove_from_task
      end
    end
    
    resources :unit_cost_estimates do
      member do
        get :add, :action => :add_to_task
        get :remove, :action => :remove_from_task
      end
    end
    
    resources :fixed_cost_estimates do
      member do
        get :add, :action => :add_to_task
        get :remove, :action => :remove_from_task
      end
    end
  end
    
  resources :labor_costs do    
    resources :labor_cost_lines, :as => :line_items
    
    collection do
      get :overview
    end
  end
  
  resources :material_costs do
    resources :material_cost_lines, :as => :line_items
    get :autocomplete_supplier_name, :on => :collection
  end
  
  resources :contracts do
    resources :bids
    resources :contract_costs

    member do
      post :add_markup, :as => :add_markup_to
    end
    
    resources :markups do
      member do
        get :add, :action => :add_to_contract
        get :remove, :action => :remove_from_contract
      end
    end
  end

  resources :tags
  
  resources :markups
  
  namespace :admin do
    resources :users
  end
  
  devise_for :users
  
  
  match 'reports', :controller => :reports, :action => :index, :as => :reports
  match 'reports/:action', :controller => :reports
  

  root :to => "projects#index"
  

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @projects = Project.scoped
    @laborers = Laborer.scoped
    @material_costs = MaterialCost.scoped
    @labor_costs = LaborCost.scoped
     
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @quantities }
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/index.html.haml
=render :partial => 'shared/project_nav', :locals => {:current => :reports}

.container
  %h1 Reports

  %hr

  -unless @labor_costs.empty?
    .left
      %h2 Labor Summary
      
      %ul
        %li=link_to 'Labor Summary for All Projects', labor_summary_projects_path
        -@projects.all.map{|p| p unless (@labor_costs.joins(:task).where('tasks.project_id = ?', p.id)).empty? }.compact.each do |project|
          %li=link_to "#{project.name} Labor Summary", labor_summary_for_project_path(project)

    .right
      %h2 Payroll Summary
      
      %ul
        -date = weekday(4, Date::today)
        %li=link_to 'Payroll Summary for All Projects', payroll_summary_projects_path('date[year]' => date.year, 'date[month]' => date.month, 'date[day]' => date.day)
        -@projects.each do |project|
          %li=link_to "#{project.name} Payroll Summary", payroll_summary_for_project_path(project, 'date[year]' => date.year, 'date[month]' => date.month, 'date[day]' => date.day)
 
 
  -projects = @projects.all.map{|p| p unless p.estimated_cost.nil? }.compact
  -unless projects.empty?
    .left
      %h2 Estimated Cost Report
      
      %ul
        -projects.each do |project|
          %li=link_to project.name, estimate_report_for_project_path(project)

  -unless @material_costs.purchase_order.empty?
    .right
      %h2 Purchase Orders
      
      %ul
        %li=link_to 'All Purchase Orders', purchase_order_list_projects_path
        -@projects.all.map{|p| p unless (@material_costs.purchase_order.joins(:task).where('tasks.project_id = ?', p.id)).empty? }.compact.each do |project|
          %li=link_to "#{project.name} Purchase Orders", purchase_order_list_for_project_path(project)
   